### ISSUE TITLE
Automated updates

### ISSUE THREAD

**Issue by jpadilla** [jpadilla/black-online#4]
@ambv this is my current idea...

- Daily cron job on Travis CI
- Check latest release via pypi/libraries.io/github releases atom feed
- Install latest version with pipenv
- Commit / push changes back to repo
- `now --public && now alias`

**Comment by ambv** [comment]
Sounds good.

**Comment by jpadilla** [comment]
@ambv just set this up in dfc89b9cb5f2ff10f93836554bd20c85525045e2. There's a cron setup to run daily on Travis CI that will deploy any updates to black automatically. Anything else you'd like to see in order to point people to this on black's readme?

**Comment by ambv** [comment]
Looks good! Go for it and add your thing to the README. You could also embed it on the front page of http://black.readthedocs.io/en/stable/ :-)

**Comment by jpadilla** [comment]
Great, will do, thanks! There’s a hidden feature you might also like.

Running this in your dev console will show a report issue link that will redirect the user to a new GitHub issue in your repo with some useful prefilled data that might help with debugging:`$('#report-button').removeClass('hidden')`
